"""Update Chat and Message models

Revision ID: 0bb09ed910fd
Revises: 420f643b3079
Create Date: 2024-08-06 00:45:38.445192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bb09ed910fd'
down_revision: Union[str, None] = '420f643b3079'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('chatbot_id', sa.Integer(), nullable=True))
    op.add_column('chats', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chats', 'chatbots', ['chatbot_id'], ['id'])
    op.create_foreign_key(None, 'chats', 'users', ['user_id'], ['id'])
    op.add_column('messages', sa.Column('chat_id', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('content', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('role', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('message_metadata', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'messages', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'chats', ['chat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'message_metadata')
    op.drop_column('messages', 'role')
    op.drop_column('messages', 'content')
    op.drop_column('messages', 'user_id')
    op.drop_column('messages', 'chat_id')
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_column('chats', 'user_id')
    op.drop_column('chats', 'chatbot_id')
    # ### end Alembic commands ###
