"""Add chatbot model

Revision ID: 420f643b3079
Revises: ea1d4c8c8e3b
Create Date: 2024-08-06 00:43:30.062757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '420f643b3079'
down_revision: Union[str, None] = 'ea1d4c8c8e3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
