"""Auto-generated migration

Revision ID: ea1d4c8c8e3b
Revises: 06bc51b03f41
Create Date: 2024-08-06 00:21:45.388749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea1d4c8c8e3b'
down_revision: Union[str, None] = '06bc51b03f41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('knowledgebases_index_id_fkey', 'knowledgebases', type_='foreignkey')
    op.drop_column('knowledgebases', 'index_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledgebases', sa.Column('index_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('knowledgebases_index_id_fkey', 'knowledgebases', 'indexes', ['index_id'], ['id'])
    # ### end Alembic commands ###
