services:
  reset-script:
    image: alpine
    volumes:
      - ./reset-script.sh:/reset-script.sh
      - postgres_data:/var/lib/postgresql/data
      - minio_data:/data
      - qdrant_data:/qdrant/storage
    command: ["/bin/sh", "-c", "apk add --no-cache bash && /bin/bash /reset-script.sh"]

volumes:
  postgres_data:
    external: true
  minio_data:
    external: true
  qdrant_data:
    external: true
